name: Update README

on: workflow_dispatch

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - run: echo "This is an updated README!" >> README.md

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5